#!/bin/bash

# Copyright (c) 2025 LukeMoyer
# Licensed under the MIT License. See LICENSE file for details.

# this is the AppImage run script

# Determine the directory of the AppRun script
APPDIR="$(dirname "$(readlink -f "${0}")")"

# Set PATH and PYTHONPATH before launching the app
export PATH="$APPDIR/usr/bin:$PATH"
export PYTHONPATH="$APPDIR/usr/lib/python3/dist-packages:$APPDIR/usr/lib/python3.11:$PYTHONPATH"

# Execute the application
exec "$APPDIR/usr/bin/python3.11" "$APPDIR/usr/bin/JSONly" "$@"
