#!/bin/bash

#   JSONly is a GUI program for interacting with and manipulating JSON files
#     Copyright (C) 2024  Luke Moyer
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

# this is the AppImage run script

# Determine the directory of the AppRun script
APPDIR="$(dirname "$(readlink -f "${0}")")"

# Set PATH and PYTHONPATH before launching the app
export PATH="$APPDIR/usr/bin:$PATH"
export PYTHONPATH="$APPDIR/usr/lib/python3/dist-packages:$APPDIR/usr/lib/python3.11:$PYTHONPATH"

# Execute the application
exec "$APPDIR/usr/bin/python3.11" "$APPDIR/usr/bin/JSONly" "$@"
